name: coc
description: "Chain of custody app."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  mobile_scanner: ^6.0.2
  camera: ^0.11.0+2
  nfc_manager: ^3.5.0
  geolocator: ^13.0.2
  http: ^1.2.2
  get_it: ^8.0.3
  flutter_secure_storage: ^9.2.2
  hive: ^2.0.0
  hive_flutter: ^1.1.0
  internet_connection_checker: ^0.0.1+4
  angles: ^2.1.1
  flutter_map: ^7.0.2
  latlong2: ^0.9.1
  path_provider: ^2.1.5
  permission_handler: ^10.2.0
  jwt_decoder: ^2.0.1
  watch_it: ^1.6.2
  import_sorter: ^4.6.0
  localstorage: ^5.0.0
  qr_flutter: ^4.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
