name: coc
description: "Chain of custody app."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  mobile_scanner: ^6.0.2
  camera: ^0.11.0+2
  nfc_manager: ^3.5.0
  geolocator: ^13.0.2
  http: ^1.2.2
  get_it: ^8.0.3
  flutter_secure_storage: ^9.2.2
  angles: ^2.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
