name: Chain Of Custody
services:

  # Database
  postgres:
    image: postgres:17
    restart: unless-stopped
    ports:
      - "127.0.0.1:9045:5432"
    volumes:
      - ./database:/var/lib/postgresql/data:rw
    environment:
      POSTGRES_PASSWORD: password
    networks:
      - bridge
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5

  # Server
  server:
    container_name: coc_server
    build:
      context: ./
      dockerfile: Dockerfile
    restart: unless-stopped
    volumes:
      - ./data:/app/data:rw
      - ./logs:/app/logs:rw
    env_file:
      - .env
    environment:
      - DATABASE_URL=postgresql://postgres:password@postgres:5432/postgres
      - ORIGIN=https://coc.hootsifer.com
    depends_on:
      - postgres
    networks:
      - bridge
      - nginx

networks:
  bridge:
  nginx:
    external: true
    name: nginx
